.PHONY: state-machine tcp-server tcp-client udp-server udp-client

state-machine:
	python3 tcp_state_machine.py
	node tcp_state_machine.js

tcp-server:
	python3 tcp_echo_server.py

tcp-client:
	python3 tcp_echo_client.py

udp-server:
	python3 udp_echo_server.py

udp-client:
	python3 udp_echo_client.py
