.PHONY: dhcp dns-server dns-client http-server

dhcp:
	python3 dhcp_dora_sim.py
	node dhcp_dora_sim.js

dns-server:
	python3 dns_server.py

dns-client:
	python3 dns_client.py

http-server:
	python3 http_server_from_scratch.py
